const list1 = [
  {
    "id": "-1",
    "name": "根菜单",
    "pId": "",
  },
  {
    "id": "1",
    "name": "系统管理",
    "enName": "systemManage",
    "path": null,
    "routerName": null,
    "pId": "0",
    "pName": null,
    "createName": "admin",
    "icon": "Tools",
    "hidden": 0,
    "sort": 1,
    "createTime": "2023-06-25 14:33:15",
    "modifyTime": "2023-06-25 14:33:15",
    "deleteTime": null,
    "version": 0
  },
  {
    "id": "13",
    "name": "商城管理",
    "enName": "mall",
    "path": "",
    "routerName": "",
    "pId": "12",
    "pName": "业务管理",
    "createName": "admin",
    "icon": "",
    "hidden": 0,
    "sort": 1,
    "createTime": "2023-06-25 14:47:03",
    "modifyTime": "2023-06-25 14:47:03",
    "deleteTime": null,
    "version": 0
  },
  {
    "id": "14",
    "name": "商品管理",
    "enName": "good",
    "path": "/bus-mall-good",
    "routerName": "BusMallGood",
    "pId": "13",
    "pName": "商城管理",
    "createName": "admin",
    "icon": "",
    "hidden": 0,
    "sort": 1,
    "createTime": "2023-06-25 14:49:10",
    "modifyTime": "2023-06-25 14:49:34",
    "deleteTime": null,
    "version": 0
  },
  {
    "id": "2",
    "name": "首页",
    "enName": "home",
    "path": "/sys-home",
    "routerName": "Home",
    "pId": "1",
    "pName": "系统管理",
    "createName": "admin",
    "icon": "HomeFilled",
    "hidden": 0,
    "sort": 1,
    "createTime": "2023-06-25 14:33:15",
    "modifyTime": "2023-06-25 14:33:15",
    "deleteTime": null,
    "version": 0
  },
  {
    "id": "12",
    "name": "业务管理",
    "enName": "business",
    "path": "",
    "routerName": "",
    "pId": "0",
    "pName": null,
    "createName": "admin",
    "icon": "Setting",
    "hidden": 0,
    "sort": 2,
    "createTime": "2023-06-25 14:33:15",
    "modifyTime": "2023-06-25 14:33:15",
    "deleteTime": null,
    "version": 0
  },
  {
    "id": "3",
    "name": "数据统计",
    "enName": "data",
    "path": "/sys-data",
    "routerName": "Data",
    "pId": "1",
    "pName": "系统管理",
    "createName": "admin",
    "icon": "View",
    "hidden": 0,
    "sort": 2,
    "createTime": "2023-06-25 14:33:15",
    "modifyTime": "2023-06-25 14:33:15",
    "deleteTime": null,
    "version": 0
  },
  {
    "id": "4",
    "name": "组织管理",
    "enName": "organization",
    "path": "/sys-organization",
    "routerName": "Organization",
    "pId": "1",
    "pName": "系统管理",
    "createName": "admin",
    "icon": "OfficeBuilding",
    "hidden": 0,
    "sort": 3,
    "createTime": "2023-06-25 14:33:15",
    "modifyTime": "2023-06-25 14:33:15",
    "deleteTime": null,
    "version": 0
  },
  {
    "id": "5",
    "name": "用户管理",
    "enName": "user",
    "path": "/sys-user",
    "routerName": "User",
    "pId": "1",
    "pName": "系统管理",
    "createName": "admin",
    "icon": "User",
    "hidden": 0,
    "sort": 4,
    "createTime": "2023-06-25 14:33:15",
    "modifyTime": "2023-06-25 14:33:15",
    "deleteTime": null,
    "version": 0
  },
  {
    "id": "6",
    "name": "菜单管理",
    "enName": "menu",
    "path": "/sys-menu",
    "routerName": "Menu",
    "pId": "1",
    "pName": "系统管理",
    "createName": "admin",
    "icon": "Menu",
    "hidden": 0,
    "sort": 5,
    "createTime": "2023-06-25 14:33:15",
    "modifyTime": "2023-06-25 14:33:15",
    "deleteTime": null,
    "version": 0
  },
  {
    "id": "7",
    "name": "接口权限管理",
    "enName": "interface",
    "path": "/sys-interface",
    "routerName": "Interface",
    "pId": "1",
    "pName": "系统管理",
    "createName": "admin",
    "icon": "Edit",
    "hidden": 0,
    "sort": 6,
    "createTime": "2023-06-25 14:33:15",
    "modifyTime": "2023-06-25 14:33:15",
    "deleteTime": null,
    "version": 0
  },
  {
    "id": "8",
    "name": "请求日志管理",
    "enName": "log",
    "path": "/sys-log",
    "routerName": "Log",
    "pId": "1",
    "pName": "系统管理",
    "createName": "admin",
    "icon": "Document",
    "hidden": 0,
    "sort": 7,
    "createTime": "2023-06-25 14:33:15",
    "modifyTime": "2023-06-25 14:33:15",
    "deleteTime": null,
    "version": 0
  },
  {
    "id": "9",
    "name": "角色权限管理",
    "enName": "auth",
    "path": "/sys-auth",
    "routerName": "Auth",
    "pId": "1",
    "pName": "系统管理",
    "createName": "admin",
    "icon": "Medal",
    "hidden": 0,
    "sort": 8,
    "createTime": "2023-06-25 14:33:15",
    "modifyTime": "2023-06-25 14:33:15",
    "deleteTime": null,
    "version": 0
  },
  {
    "id": "10",
    "name": "定时任务管理",
    "enName": "task",
    "path": "/sys-task",
    "routerName": "Task",
    "pId": "1",
    "pName": "系统管理",
    "createName": "admin",
    "icon": "Guide",
    "hidden": 0,
    "sort": 9,
    "createTime": "2023-06-25 14:33:15",
    "modifyTime": "2023-06-25 14:33:15",
    "deleteTime": null,
    "version": 0
  },
  {
    "id": "11",
    "name": "IP封禁管理",
    "enName": "ip",
    "path": "/sys-ip",
    "routerName": "Ip",
    "pId": "1",
    "pName": "系统管理",
    "createName": "admin",
    "icon": "Lock",
    "hidden": 0,
    "sort": 10,
    "createTime": "2023-06-25 14:33:15",
    "modifyTime": "2023-06-25 14:33:15",
    "deleteTime": null,
    "version": 0
  }
]

const list2 = [
  {
    "id": "0",
    "value": "顶级组织",
    "pId": "",
    "departmentCode": "0"
  },
  {
    "id": "1",
    "value": "一级组织",
    "pId": "0",
    "departmentCode": "1"
  }
]